Repository specmock/specmock, pull requests merged in 2023-12, with the labels that each got.

#1 Initial Spec from spring-web-bind
  .github/workflows/ci.yml
  CONTRIBUTING.md
  README.md
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lint.gradle
  publishing.gradle
  settings/checkstyle/checkstyle-suppressions.xml
  settings/checkstyle/checkstyle.xml
  settings/intellij_idea/settings.jar
  specmock/build.gradle
  specmock/src/main/java/io/specmock/core/ArmeriaHttpSpecHandler.java
  specmock/src/main/java/io/specmock/core/ArmeriaHttpSpecServer.java
  specmock/src/main/java/io/specmock/core/ArmeriaRouteGenerator.java
  specmock/src/main/java/io/specmock/core/HttpExchange.java
  specmock/src/main/java/io/specmock/core/HttpExchangeBuilder.java
  specmock/src/main/java/io/specmock/core/HttpMethod.java
  specmock/src/main/java/io/specmock/core/HttpRoute.java
  specmock/src/main/java/io/specmock/core/HttpRouteClassMapping.java
  specmock/src/main/java/io/specmock/core/HttpSpec.java
  specmock/src/main/java/io/specmock/core/HttpSpecBuilder.java
  specmock/src/main/java/io/specmock/core/HttpSpecServer.java
  specmock/src/main/java/io/specmock/core/HttpSpecServerBuilder.java
  specmock/src/main/java/io/specmock/core/HttpStatus.java
  specmock/src/main/java/io/specmock/core/SpringWebHttpSpecBuilder.java
  specmock/src/main/java/io/specmock/core/package-info.java
  specmock/src/test/java/io/specmock/core/ArmeriaRouteGeneratorTest.java
  specmock/src/test/java/io/specmock/core/HttpExchangeTest.java
  specmock/src/test/java/io/specmock/core/HttpRouteTest.java
  specmock/src/test/java/io/specmock/core/HttpSpecBuilderTest.java
  specmock/src/test/java/io/specmock/core/HttpSpecServerBuilderTest.java
  specmock/src/test/java/io/specmock/core/HttpStatusTest.java
  specmock/src/test/java/io/specmock/core/SpringWebHttpSpecBuilderTest.java
  specmock/src/test/java/io/specmock/core/SpringWebIncorrectTest.java
  specmock/src/test/java/io/specmock/core/SpringWebTest.java
  specmock/src/test/java/io/specmock/core/example/Example1Request.java
  specmock/src/test/java/io/specmock/core/example/Example1Response.java
  specmock/src/test/java/io/specmock/core/example/Example2Response.java
  specmock/src/test/java/io/specmock/core/example/Example3Request.java
  specmock/src/test/java/io/specmock/core/example/Example3Response.java
  specmock/src/test/java/io/specmock/core/example/Example4Request.java
  specmock/src/test/java/io/specmock/core/example/Example4Response.java
  specmock/src/test/java/io/specmock/core/example/Example5Request.java
  specmock/src/test/java/io/specmock/core/example/Example5Response.java
  specmock/src/test/java/io/specmock/core/example/Example6Request.java
  specmock/src/test/java/io/specmock/core/example/Example6Response.java
  specmock/src/test/java/io/specmock/core/example/Example7Request.java
  specmock/src/test/java/io/specmock/core/example/Example7Response.java
  specmock/src/test/java/io/specmock/core/example/Example8Response.java
  specmock/src/test/java/io/specmock/core/example/ExampleApi.java
  specmock/src/test/java/io/specmock/core/example/ExampleEmptyApi.java
Labels: enhancement

#2 Support Spring rest mapping annotation
  specmock/src/main/java/io/specmock/core/SpringWebHttpSpecBuilder.java
  specmock/src/test/java/io/specmock/core/SpringRestWebTest.java
  specmock/src/test/java/io/specmock/core/example/ExampleRestApi.java
Labels: enhancement

#4 Support jackson-module-kotlin
  specmock/build.gradle
  specmock/src/main/java/io/specmock/core/ArmeriaHttpSpecHandler.java
  specmock/src/test/java/io/specmock/core/SpringRestWebTest.java
  specmock/src/test/java/io/specmock/core/SpringWebTest.java
Labels: enhancement

#5 Fixed README.md typo
  README.md
Labels: documentation

#7 add depedency testImplementation block for build.gradle.kts
  README.md
Labels: documentation, enhancement

#8 Correct typo in some test
  specmock/src/test/java/io/specmock/core/HttpRouteTest.java
  specmock/src/test/java/io/specmock/core/SpringRestWebTest.java
  specmock/src/test/java/io/specmock/core/SpringWebTest.java
Labels: enhancement

#9 Register JavaTimeModule with ObjectMapper for enhanced date/time handling
  specmock/build.gradle
  specmock/src/main/java/io/specmock/core/ArmeriaHttpSpecHandler.java
  specmock/src/test/java/io/specmock/core/ObjectMapperTest.java
Labels: enhancement
